apiVersion: v1
kind: ReplicationController
metadata:
  name: app-2-controller
spec:
  replicas: 3
  selector:
    app: app2-started
  template:
    metadata:
      labels:
        app: app2-started
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: app2-started
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: http-port
          containerPort: 80
