apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-ds-toleration-ds
  labels:
    app: hello-ds-toleration
spec:
  selector:
    matchLabels:
      app: hello-ds-toleration
  template:
    metadata:
      labels:
        app: hello-ds-toleration
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: node-port
          containerPort: 80
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
