# Base Image
FROM ubuntu:16.04

# Who's the maintainer
MAINTAINER Amit Vashist <amitvashist7@outlook.com>

# Update the APT Repo
RUN echo "Welcome to the world of Docker Image" >> /var/amit.html 

# Bring UP Apache Service
CMD ["/bin/sleep 300"]
